  name: Deploy practice project
  on: push
  jobs:
    lint_test_deploy:
      runs-on: ubuntu-latest
      steps:
        - name: checkout code
          uses: actions/checkout@v3
        - name: npm package install
          run: npm install
        - name: lint
          run: npm run lint
        - name: build
          run: npm run build
        - name: test
          run: npm run test

